2025-05-14 22:29:58,781 | INFO | Wczytano kontrakt: 0xe7f1725E7734CE288F8367e1Bb143E90bb3F0512
2025-05-14 22:30:16,407 | INFO | Dodawanie dokumentu: tmp (pdf) | Plik: /Users/grzegorz/Documents/PK/sem3/BLOCKCHAIN/Blockchain/DocChain/src/data/sample_docs/example.pdf
2025-05-14 22:32:35,856 | INFO | Wczytano kontrakt: 0xe7f1725E7734CE288F8367e1Bb143E90bb3F0512
2025-05-14 22:32:54,848 | INFO | Dodawanie dokumentu: plik (pdf) | Plik: /Users/grzegorz/Documents/PK/sem3/BLOCKCHAIN/Blockchain/DocChain/src/data/sample_docs/example.pdf
2025-05-14 22:32:54,887 | ERROR | Błąd podczas dodawania dokumentu
Traceback (most recent call last):
  File "/Users/grzegorz/Documents/PK/sem3/BLOCKCHAIN/Blockchain/DocChain/src/src/gui/blockchainApp.py", line 237, in handle_add_document
    add_document(self.contract, self.web3, content, name, doc_type)
    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/grzegorz/Documents/PK/sem3/BLOCKCHAIN/Blockchain/DocChain/src/src/document_handler.py", line 25, in add_document
    tx_hash, block, status = send_transaction(web3, txn)
                             ~~~~~~~~~~~~~~~~^^^^^^^^^^^
  File "/Users/grzegorz/Documents/PK/sem3/BLOCKCHAIN/Blockchain/DocChain/src/src/blockchain.py", line 82, in send_transaction
    tx_hash = web3.eth.send_raw_transaction(signed_txn.raw_transaction)
  File "/Users/grzegorz/Documents/PK/sem3/BLOCKCHAIN/Blockchain/DocChain/src/venv/lib/python3.13/site-packages/web3/eth/eth.py", line 396, in send_raw_transaction
    return self._send_raw_transaction(transaction)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/Users/grzegorz/Documents/PK/sem3/BLOCKCHAIN/Blockchain/DocChain/src/venv/lib/python3.13/site-packages/web3/module.py", line 112, in caller
    result = w3.manager.request_blocking(
        method_str, params, error_formatters, null_result_formatters
    )
  File "/Users/grzegorz/Documents/PK/sem3/BLOCKCHAIN/Blockchain/DocChain/src/venv/lib/python3.13/site-packages/web3/manager.py", line 232, in request_blocking
    return self.formatted_response(
           ~~~~~~~~~~~~~~~~~~~~~~~^
        response, params, error_formatters, null_result_formatters
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/Users/grzegorz/Documents/PK/sem3/BLOCKCHAIN/Blockchain/DocChain/src/venv/lib/python3.13/site-packages/web3/manager.py", line 198, in formatted_response
    validate_rpc_response_and_raise_if_error(
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        response,
        ^^^^^^^^^
    ...<3 lines>...
        params=params,
        ^^^^^^^^^^^^^^
    )
    ^
  File "/Users/grzegorz/Documents/PK/sem3/BLOCKCHAIN/Blockchain/DocChain/src/venv/lib/python3.13/site-packages/web3/_utils/validation.py", line 401, in validate_rpc_response_and_raise_if_error
    raise web3_rpc_error
web3.exceptions.Web3RPCError: {'code': -32603, 'message': "Error: VM Exception while processing transaction: reverted with reason string 'Document already exists'", 'data': {'message': "Error: VM Exception while processing transaction: reverted with reason string 'Document already exists'", 'txHash': '0x59895aa4c027211b09b905c6b2ee7dcfcf8a8cc404f650860c84c9f38bb7f6b1', 'data': '0x08c379a000000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000000000000000017446f63756d656e7420616c726561647920657869737473000000000000000000'}}
2025-05-14 22:33:20,221 | INFO | Weryfikacja dokumentu: /Users/grzegorz/Documents/PK/sem3/BLOCKCHAIN/Blockchain/DocChain/src/data/sample_docs/example.pdf
